language: php

php:
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

env:
  - DB_USERNAME=travis

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE yarcode_test;'

script:
  - composer validate --strict
