language: php

php:
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

services:
  - memcached
  - mysql
  - redis-server

env:
  - DB_USERNAME=travis

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.0/elasticsearch-2.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.0.deb && sudo service elasticsearch restart

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction
# setup application:
  - |
    ./init --env=Development
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" frontend/config/main.php
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" backend/config/main.php

before_script:
  - mysql -e 'CREATE DATABASE yarcode_test;'
  - php yii_test migrate --interactive=0

script:
  - composer validate --strict
